[package]
name = "sylvan_number"
version = "0.1.4"
edition = "2021"
description = "My own big number implementation, just for my own uses."
license = "GPL-3.0-or-later"
readme = "README.md"

[dependencies]
algebra_kit = "0.1.8"
rand = "0.8.5"
